spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/alumni_connect}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:5000}
spring.web.cors.allowed-origins=*
spring.datasource.username=${alumni_connect_db1_user}
spring.datasource.password=${0rLjfrnsofzcfICmr6uOrrkU76UezV3Y}
